### PR TITLE
viewer: Filter input loses focus on double-enter

### LINKED ISSUE #297: Filter input loses focus on double-enter
The double-enter is used to start a search; it also removes the cursor from the input. The user has to click on the input again to enter another filter.

### PR DESCRIPTION
**Pull request by zeroinformatique**
This is related to issue #177
The focus won't change anymore if we are in an INPUT field.

GitHub: closes #297

### CODE REVIEW

**Review by pacien — CHANGES_REQUESTED** [review]
This impedes keyboard navigation for scrolling in the main content container as described in #177: using the up/down arrows now opens a useless "No match" suggestion menu.

I agree that we should keep the focus on the input field when pressing "enter", but we should certainly transfer the focus to the main content div when pressing the up/down arrows or page up/down keys.

Note that the "tab" key also has a strange behaviour regarding focus (#300).
Could you also look at that issue at the same time?

**Comment by zeroinformatique** [comment]
#300 will be fixed in another branch.

The only way I found to deal with this scrolling issue was to scroll programmatically.
Can you give a try to the version I pushed and tell me if that works decently?

**Comment by pacien** [comment]
The JS scroll is quirky: repeated key presses are missed and continuous presses create some laggy scroll, jumping around in batches. This is not usable as is.

Would it be possible to capture some events (arrow key presses) and inject them to the other DOM element and let it handle the scroll natively instead of setting the scroll distance manually?

**Comment by zeroinformatique** [comment]
That's what I tried, but it doesn't work for the very first input (which is used to switch the focus).
It's very confusing to hit page-down, and it doesn't work the first time; try again and now it works.
I did a dispatch of the keyboard event to the element, but you can't force a scroll through an event programmatically; apparently it's a security feature.
This is why I tried to handle the scroll itself, but it's very limited and, as you noticed, quite crappy.

**Comment by zeroinformatique** [comment]
After a phone call, we'll try an hybrid method between both:
- The first keypress will switch the focus, and simulate a scroll
- The other keypresses will use the natural scrolling

**Comment by pacien** [comment]
This has been fixed in 00510820a2794efcadbc83f7f8b54318fe198ecb.

**Pull request closed without merging**
