### PR TITLE
index: use references to a combined tag list

### PR DESCRIPTION
**Pull request by pacien**
- compiler: move decodeYamlFile util from Input to Files
- compiler/index: aggregate tags in list and use index references
- viewer: add adapter for int tag references
- viewer: remove some deprecated stringTags adapter uses

### CODE REVIEW

**Comment by zeroinformatique** [comment]
We'll have to discuss that one.
I don't want to push @Deprecated new code, especially with getters that redefine a property.
We should either adapt the code properly, or just wait for the index rewrite.

**Review by zeroinformatique — CHANGES_REQUESTED** [review]
We'll have to discuss that one.
I don't want to push @deprecated new code, especially with getters that redefine a property.
We should either adapt the code properly, or just wait for the index rewrite.

**Comment by pacien** [comment]
Quoting zeroinformatique (2022-10-25 01:31:15)
> @zeroinformatique requested changes on this pull request.
> 
> We'll have to discuss that one. I don't want to push @deprecated new
> code, especially with getters that redefine a property. We should
> either adapt the code properly

Fair enough. I removed the remaining use of the adapter as well as the
adapter itself, so that we don't introduce deprecated code.

> , or just wait for the index rewrite.

I prefer merging this into develop now since this is ready and working.
I don't like stacking multiple branches and getting far away from the
main one.

**Review by zeroinformatique — CHANGES_REQUESTED** [review]
This breaks the retro-compatibility of the gallery, and especially the cache.
A user shouldn't have to recreate his gallery from zero for a small technical update; this takes way too long on large galleries.

This enhancement requires cache retro-compatibility in the compiler before being acceptable.

**Comment by pacien** [comment]
Quoting zeroinformatique (2022-10-27 08:58:11)
> This breaks the retro-compatibility of the gallery, and especially the
> cache. A user shouldn't have to recreate his gallery from zero for a
> small technical update; this takes way too long on large galleries.
> 
> This enhancement requires cache retro-compatibility in the compiler
> before being acceptable.

The cache isn't source data and is simply automatically invalidated as
expected. I hear the concern on big galleries. Cache
"retro-compatibility", or migration, would be too complex for a one-off.

I propose simply postponing the change to the next major version.

This and other changes building up on this new index structure will take
place on the `staging-major` branch instead. It will follow `develop`
without hindering smaller changes and bug fixes for the upcoming minor
versions.

Is this proposal acceptable for the next major version?

**Review by zeroinformatique — APPROVED** [review]
LGTM; observed 8% gain in json size.

**Pull request merged**
